FROM registry.redhat.io/ubi8:8.6-754 as builder

RUN INSTALL_PKGS=" \
      rust-toolset \
      cmake \
      make \
      git \
      openssl-devel \
      llvm-toolset \
      cyrus-sasl \
      python36 \
      llvm \
      cyrus-sasl-devel \
      libtool \
      " && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all

RUN mkdir -p /src ~/.cargo/bin && curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ~/.cargo/bin

WORKDIR /src
COPY . /src
