FROM registry.redhat.io/ubi9/ubi:latest

RUN INSTALL_PKGS=" \
      cmake \
      libarchive \
      gcc-c++ \
      make \
      git \
      perl \
      openssl-devel \
      llvm-toolset \
      cyrus-sasl \
      llvm \
      cyrus-sasl-devel \
      libtool \
      " && \
    dnf install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    dnf clean all

ENV HOME=/root
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain 1.92.0 -y
ENV CARGO_HOME=$HOME/.cargo
ENV PATH=$CARGO_HOME/bin:$PATH

RUN mkdir -p /src

WORKDIR /src
COPY . /src

# Initialize git repository for build scripts that need git metadata
RUN cd /src && \
    git init && \
    git config user.email "ci@redhat.com" && \
    git config user.name "CI" && \
    git add . && \
    git commit --no-verify -m "CI build"

# Use bundled protoc and set environment
RUN chmod +x /src/thirdparty/protoc/protoc-linux-x86_64
ENV PROTOC=/src/thirdparty/protoc/protoc-linux-x86_64
ENV PATH=/src/thirdparty/protoc:$PATH

RUN mkdir -p $CARGO_HOME && chmod -R 777 /src $CARGO_HOME $HOME
RUN mkdir -p ~/.cargo/bin && \
    for plugin in nextest deny; do \
        ln -s /src/thirdparty/cargo-${plugin}/cargo-${plugin}-linux-x86_64 ~/.cargo/bin/cargo-${plugin}; \
	done

